#!/usr/bin/env bash
# Install haproxy
FOO="\
frontend load_balancer
    bind *:80
    mode http
    default_backend foo
    
backend foo
    balance roundrobin
    server 2158-web-01 104.196.120.195:80 check
    server 2158-web-02 34.74.6.247:80 check
"
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "$FOO" >> /etc/haproxy/haproxy.cfg
service haproxy start