#!/usr/bin/env bash
# Bash script that displays number from 1 to 20
number=1
while (( "$number" < 21 ))
do
	echo $number

	case $number in

		4)
		echo "bad luch from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	esac
	(( number++ ))
done
